version: "3.9"

services:
  web:
    build: .
    container_name: vite_app
    # ports:
    #   - "5173:80"   # access app at http://localhost:5173
    restart: unless-stopped
    networks:
      - arifa-network
    environment:
      - NODE_ENV=production
      - TOKEN_SECRET=AIDA#$$$#$@$FGSF

networks:
  arifa-network:
    external: true